name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.lalle1 }}
        password: ${{ secrets.As10101010 }}

    - name: Build Docker image
      run: docker build -t lalle1/pi:latest .

    - name: Push Docker image
      run: docker push lalle1/pi:latest