# Generated by Django 5.1.3 on 2025-01-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('technologies', models.TextField()),
                ('semester', models.CharField(max_length=50)),
                ('students_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SupNumProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('technologies', models.TextField()),
                ('supervisor', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=50)),
                ('max_students', models.IntegerField()),
            ],
        ),
    ]
