# Generated by Django 5.1.3 on 2025-01-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('SupNum', 'SupNum'), ('Personnel', 'Personnel')], default='SupNum', max_length=20)),
                ('student_names', models.TextField(help_text='Entrez les noms des étudiants séparés par des virgules')),
            ],
        ),
    ]
